--
-- PostgreSQL database dump
--

-- Dumped from database version 16.2 (Debian 16.2-1.pgdg120+2)
-- Dumped by pg_dump version 16.0

-- Started on 2024-05-19 15:01:35

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 217 (class 1259 OID 32880)
-- Name: Categories; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Categories" (
    "Id" bigint NOT NULL,
    "Name" character varying(500) NOT NULL,
    "IsDeleted" boolean NOT NULL
);


ALTER TABLE public."Categories" OWNER TO postgres;

--
-- TOC entry 216 (class 1259 OID 32879)
-- Name: Categories_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Categories" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Categories_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3373 (class 0 OID 32880)
-- Dependencies: 217
-- Data for Name: Categories; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Categories" ("Id", "Name", "IsDeleted") FROM stdin;
2	Thực phẩm chức năng	f
3	Chăm sóc cá nhân	f
4	Thiết bị y tế	f
8	Dược phẩm	f
9	Mỹ phẩm	f
\.


--
-- TOC entry 3379 (class 0 OID 0)
-- Dependencies: 216
-- Name: Categories_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Categories_Id_seq"', 9, true);


--
-- TOC entry 3228 (class 2606 OID 32886)
-- Name: Categories PK_Categories; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Categories"
    ADD CONSTRAINT "PK_Categories" PRIMARY KEY ("Id");


-- Completed on 2024-05-19 15:01:35

--
-- PostgreSQL database dump complete
--

