--
-- PostgreSQL database dump
--

-- Dumped from database version 16.2 (Debian 16.2-1.pgdg120+2)
-- Dumped by pg_dump version 16.0

-- Started on 2024-05-19 15:02:23

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 219 (class 1259 OID 32888)
-- Name: Ingredients; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Ingredients" (
    "Id" bigint NOT NULL,
    "Name" character varying(500) NOT NULL,
    "IsDeleted" boolean NOT NULL
);


ALTER TABLE public."Ingredients" OWNER TO postgres;

--
-- TOC entry 218 (class 1259 OID 32887)
-- Name: Ingredients_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Ingredients" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Ingredients_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3373 (class 0 OID 32888)
-- Dependencies: 219
-- Data for Name: Ingredients; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Ingredients" ("Id", "Name", "IsDeleted") FROM stdin;
1	vitamin1	f
2	vitamin2	f
3	vitamin3	f
4	Vitamin C	f
5	Chiết xuất nhân sâm	f
6	Vitamin B12	f
7	Vitamin B6	f
8	Vitamin B2	f
9	Vitamin B1	f
10	Vitamin PP	f
11	Vitamin C	f
12	Magie oxide	f
13	Calcium (Ca+)	f
14	Vitamin K2	f
15	Vitamin D3	f
16	Magnesium	f
17	Zinc	f
18	Bạch hoa xà thiệt thảo	f
19	Tiêu đen	f
20	Sinh khương	f
21	Bạch Đậu Khấu	f
22	Ổi lá	f
23	Lá đu đủ	f
24	Nghệ vàng	f
27	Yến sào chưng sẵn	f
28	Đường phèn	f
29	Hương tổng hợp	f
30	Chất bảo quản	f
31	Vitamin K2	f
32	Đông trùng hạ thảo	f
33	Nước	f
34	Nhân Sâm	f
35	Tinh dầu hoa anh thảo	f
36	Lepidium meyenii	f
37	Trinh nữ	f
38	Glucosamin sulfat 2KCL	f
39	Methyl sulfonyl methan (MSM)	f
40	Chondroitin sulfate	f
41	Bromelain 2500 GDU/g	f
42	Collagen thủy phân type 1	f
43	Calcium Carbonate	f
44	Vitamin D3	f
45	Vitamin K2 MK7	f
46	Kẽm (kẽm oxit)	f
47	Hạt dẻ ngựa	f
48	Hesperidin	f
49	Rutin	f
50	Witch hazel	f
51	Lecithin	f
52	Cà gai leo	f
53	Nhân trần	f
54	Kẽm Gluconat	f
55	Sodium clorid	f
56	Ion Alkaline	f
57	Glycerin	f
58	Peg-8	f
59	Hydrated silica	f
60	Calcium	f
61	Cocamidopropyl betaine	f
62	Titanium dioxide	f
63	Carbomer	f
64	Hosphosilicate (NOVAMIN)	f
65	Nhựa	f
66	Coco-betaine	f
67	Disodium Laureth Sulfosuccinate	f
68	PEG-7 Glyceryl Cocoate	f
69	Sodium Laureth Sulfate	f
70	Peg-120 Methyl Glucose Dioleate	f
71	Calcium gluconate	f
72	Butylene glycol	f
73	Isononyl Isononanoate	f
74	Octocrylene	f
75	Niacinamide	f
76	Butyrospermum Parkii Butter	f
77	Titanium dioxide	f
78	Xylitylglucoside, Anhydroxylitol, Xylitol	f
79	cetearyl alcohol, Dicetyl Phosphate, Ceteth-10 Phosphate	f
80	alpha-Arbutin	f
\.


--
-- TOC entry 3379 (class 0 OID 0)
-- Dependencies: 218
-- Name: Ingredients_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Ingredients_Id_seq"', 80, true);


--
-- TOC entry 3228 (class 2606 OID 32894)
-- Name: Ingredients PK_Ingredients; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Ingredients"
    ADD CONSTRAINT "PK_Ingredients" PRIMARY KEY ("Id");


-- Completed on 2024-05-19 15:02:23

--
-- PostgreSQL database dump complete
--

