--
-- PostgreSQL database dump
--

-- Dumped from database version 16.2 (Debian 16.2-1.pgdg120+2)
-- Dumped by pg_dump version 16.0

-- Started on 2024-05-19 15:03:10

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 227 (class 1259 OID 32947)
-- Name: ProductUnits; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."ProductUnits" (
    "Id" bigint NOT NULL,
    "ProductId" uuid NOT NULL,
    "UnitId" uuid NOT NULL,
    "Price" numeric(18,2) NOT NULL,
    "IsDefault" boolean DEFAULT false NOT NULL,
    "IsMinUnit" boolean DEFAULT false NOT NULL,
    "Level" integer NOT NULL,
    "Ratio" integer NOT NULL,
    "IsDeleted" boolean NOT NULL
);


ALTER TABLE public."ProductUnits" OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 32946)
-- Name: ProductUnits_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."ProductUnits" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ProductUnits_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3379 (class 0 OID 32947)
-- Dependencies: 227
-- Data for Name: ProductUnits; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."ProductUnits" ("Id", "ProductId", "UnitId", "Price", "IsDefault", "IsMinUnit", "Level", "Ratio", "IsDeleted") FROM stdin;
102	46c0ea53-8470-40ea-bd3f-fd9baf4a6fd1	95f11e82-c226-4169-9f10-e6fa2b90803d	32000.00	t	t	1	1	f
103	e2dd16b7-1e6a-4442-a17c-1e28638de025	e2346d73-8a53-4590-ad70-49c5c08d9436	112000.00	t	t	1	1	f
104	e9e6f6de-a912-4ca9-a3d5-e63a7b8bd0c9	e2346d73-8a53-4590-ad70-49c5c08d9436	185000.00	t	t	1	1	f
105	bae39267-5e5e-4afb-aa61-89980bf63eb6	e2346d73-8a53-4590-ad70-49c5c08d9436	57989.00	t	t	1	1	f
106	00072e09-ec13-4366-9149-fe5e0fe24faf	e2346d73-8a53-4590-ad70-49c5c08d9436	130000.00	t	t	1	1	f
107	c9655d8c-025b-4746-8535-6dccf5628d30	e2346d73-8a53-4590-ad70-49c5c08d9436	94000.00	t	t	1	1	f
108	2bdd48d7-b5a7-498d-a894-139f1870152d	174fddb3-12dd-4043-ba7b-6054bf3a8d2a	178000.00	t	t	1	1	f
109	c75864ca-bb09-4128-9401-9766a3640a5a	24d16932-c08a-482f-9850-39116d13f801	63000.00	t	t	1	1	f
110	081c0402-ca8f-40d1-981f-8d84fb6b2a1d	174fddb3-12dd-4043-ba7b-6054bf3a8d2a	279000.00	t	t	1	1	f
111	d387afd7-c368-4ddd-b3fd-f06cc9a3789f	e2346d73-8a53-4590-ad70-49c5c08d9436	154000.00	t	t	1	1	f
13	29e04118-7b33-439d-9fa3-e6b4e316a622	7749e1f7-ffd5-403c-a7e8-6be545997c0c	236000.00	t	f	1	6	f
14	29e04118-7b33-439d-9fa3-e6b4e316a622	5924ee66-5ba9-435e-83f4-2c5762575890	50000.00	f	t	2	1	f
112	aa212c32-5b7c-4742-8225-2d4a5c61def3	24d16932-c08a-482f-9850-39116d13f801	166000.00	t	t	1	1	f
113	fea3bc0c-030c-4ed9-b209-468330b143fc	24d16932-c08a-482f-9850-39116d13f801	245000.00	t	t	1	1	f
114	746f2594-c421-4a3d-a427-8516c0b11e15	e2346d73-8a53-4590-ad70-49c5c08d9436	150000.00	t	t	1	1	f
54	b62a0173-10c0-4d7e-85bb-db59522526e3	e2346d73-8a53-4590-ad70-49c5c08d9436	144000.00	t	t	1	1	f
8	4cfdb45c-5eff-4bf0-8362-4a8711083d9a	e2346d73-8a53-4590-ad70-49c5c08d9436	570000.00	t	t	1	1	f
10	ca1452e6-ef50-4641-afff-f8a7c158d11f	e2346d73-8a53-4590-ad70-49c5c08d9436	180000.00	t	t	1	1	f
79	5eda1707-922f-4630-996c-0546d6a79b9d	e2346d73-8a53-4590-ad70-49c5c08d9436	175000.00	t	t	1	1	f
80	9ed7700c-e13e-4a9f-a81c-95524f2fca32	e2346d73-8a53-4590-ad70-49c5c08d9436	680000.00	t	t	1	1	f
81	151db02f-0359-4057-9093-fcd3cc13af53	e2346d73-8a53-4590-ad70-49c5c08d9436	920000.00	t	t	1	1	f
82	7a9e8433-7466-470d-80f0-75c758010ac5	e2346d73-8a53-4590-ad70-49c5c08d9436	650000.00	t	t	1	1	f
83	e4384936-f170-4738-840a-b9f43c152292	e2346d73-8a53-4590-ad70-49c5c08d9436	250000.00	t	t	1	1	f
84	14452697-bf58-4d33-af0d-3cebafa5f358	e2346d73-8a53-4590-ad70-49c5c08d9436	48000.00	t	t	1	1	f
85	7685a988-43bd-4659-acdc-ce46b8427b63	174fddb3-12dd-4043-ba7b-6054bf3a8d2a	21000.00	t	t	1	1	f
86	643a5948-4791-447b-b6d1-74cf0dec6548	24d16932-c08a-482f-9850-39116d13f801	82000.00	t	t	1	1	f
87	f280a21b-d26a-41b8-a383-d8ca5fca9bac	e2346d73-8a53-4590-ad70-49c5c08d9436	960000.00	t	t	1	1	f
88	db5d08ee-9a30-42fd-8665-34e16e175e26	e2346d73-8a53-4590-ad70-49c5c08d9436	1100000.00	t	t	1	1	f
89	ca6e2dfd-3460-451d-8a3c-243086157524	e2346d73-8a53-4590-ad70-49c5c08d9436	1512000.00	t	t	1	1	f
90	7d2eb081-8045-493c-8461-932835e21fea	e2346d73-8a53-4590-ad70-49c5c08d9436	70000.00	t	t	1	1	f
91	2c6e7660-a780-4501-a444-bfa0d04e3d9d	e2346d73-8a53-4590-ad70-49c5c08d9436	1992000.00	t	t	1	1	f
92	0676c6c6-1f00-4de9-b9ca-9f3c8e11243a	e2346d73-8a53-4590-ad70-49c5c08d9436	1950000.00	t	t	1	1	f
93	d4b76d1a-40d4-4560-a5ca-3250a9efe026	e2346d73-8a53-4590-ad70-49c5c08d9436	185000.00	t	t	1	1	f
94	0a249e49-8d3e-4fe8-9d15-572c4329abf1	e2346d73-8a53-4590-ad70-49c5c08d9436	1432000.00	t	t	1	1	f
95	b708ded8-2118-493c-9b19-7ea19cb696c1	24d16932-c08a-482f-9850-39116d13f801	390000.00	t	t	1	1	f
96	97eb94e3-6c6d-4400-a469-a5af3c52cbcb	e2346d73-8a53-4590-ad70-49c5c08d9436	339000.00	t	t	1	1	f
97	e5707dad-0c1e-4a1c-8b2a-9658e028ccf6	174fddb3-12dd-4043-ba7b-6054bf3a8d2a	145000.00	t	t	1	1	f
98	52561447-6304-42fe-9488-922953228163	24d16932-c08a-482f-9850-39116d13f801	165000.00	t	t	1	1	f
99	b3d97fc4-078c-47fb-a5ae-4127ffacb580	e2346d73-8a53-4590-ad70-49c5c08d9436	1110000.00	t	t	1	1	f
100	4a5fee1f-e425-4249-a46b-da8c2125fdbb	e2346d73-8a53-4590-ad70-49c5c08d9436	70000.00	t	t	1	1	f
\.


--
-- TOC entry 3385 (class 0 OID 0)
-- Dependencies: 226
-- Name: ProductUnits_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."ProductUnits_Id_seq"', 114, true);


--
-- TOC entry 3232 (class 2606 OID 32953)
-- Name: ProductUnits PK_ProductUnits; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ProductUnits"
    ADD CONSTRAINT "PK_ProductUnits" PRIMARY KEY ("Id");


--
-- TOC entry 3229 (class 1259 OID 32967)
-- Name: IX_ProductUnits_ProductId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_ProductUnits_ProductId" ON public."ProductUnits" USING btree ("ProductId");


--
-- TOC entry 3230 (class 1259 OID 32968)
-- Name: IX_ProductUnits_UnitId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_ProductUnits_UnitId" ON public."ProductUnits" USING btree ("UnitId");


--
-- TOC entry 3233 (class 2606 OID 32954)
-- Name: ProductUnits FK_ProductUnits_Products_ProductId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ProductUnits"
    ADD CONSTRAINT "FK_ProductUnits_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES public."Products"("Id") ON DELETE CASCADE;


--
-- TOC entry 3234 (class 2606 OID 32959)
-- Name: ProductUnits FK_ProductUnits_Units_UnitId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ProductUnits"
    ADD CONSTRAINT "FK_ProductUnits_Units_UnitId" FOREIGN KEY ("UnitId") REFERENCES public."Units"("Id") ON DELETE CASCADE;


-- Completed on 2024-05-19 15:03:10

--
-- PostgreSQL database dump complete
--

